version: "3.3"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=API_ID # change this to your ID
       - API_HASH=API_HASH # change this to your HASH
       - BOT_TOKEN=BOT_TOKEN # enter your bot token
       - BIN_CHANNEL=BIN_CHANNEL # paste channel ID
      ports:
       - 127.0.0.1:8000:8000
